export const SESSION_START = "SESSION_START"
export const SESSION_TICK = "SESSION_TICK"
export const SESSION_PAUSE = "SESSION_PAUSE"
export const SESSION_RESET = "SESSION_RESET"
export const SESSION_INTERRUPT = "SESSION_INTERRUPT"
export const SESSION_COMPLETE = "SESSION_COMPLETE"
export const SESSION_QUIT = "SESSION_QUIT"



export const TIMER_EDIT_APPLY = "TIMER_EDIT_APPLY"
export const TIMER_EDIT = "TIMER_EDIT"

export const AUDIO_BEGIN_LOAD = "AUDIO_BEGIN_LOAD"
export const AUDIO_LOADED = "AUDIO_LOADED"
export const AUDIO_PLAY = "AUDIO_PLAY"
export const AUDIO_STOP = "AUDIO_STOP"
export const AUDIO_FILE_EDIT = "AUDIO_FILE_EDIT"
export const AUDIO_VOLUME_EDIT = "AUDIO_VOLUME_EDIT"

export const LOAD_STATE = "LOAD_STATE"
export const SAVE_STATE = "SAVE_STATE"
export const CLEAR_STATE = "CLEAR_STATE"
